### ISSUE TITLE
ARM support for Linux

### ISSUE THREAD

**Issue by cjaentsch** [fiskaly/fiskaly-kassensichv-sma#1]
Is there a planned implementation for ARM Linux as well? We have a lot of customers out there with a Raspberry Pi as the central communication unit (which will serve as SMA).

**Comment by pgaubatz** [comment]
We've just added an experimental build for linux ARM/ARM64 in #2.
Maybe you could give it a try?

**Comment by cjaentsch** [comment]
Unfortunately it does not work...

I get an Error:

java.lang.UnsatisfiedLinkError: /tmp/com.fiskaly.kassensichv.sma-linux-arm.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
	at jnr.ffi.provider.jffi.NativeLibrary.loadNativeLibraries(NativeLibrary.java:87)
	at jnr.ffi.provider.jffi.NativeLibrary.getNativeLibraries(NativeLibrary.java:70)
	at jnr.ffi.provider.jffi.NativeLibrary.getSymbolAddress(NativeLibrary.java:49)
	at jnr.ffi.provider.jffi.NativeLibrary.findSymbolAddress(NativeLibrary.java:59)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:158)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.loadLibrary(AsmLibraryLoader.java:89)
	at jnr.ffi.provider.jffi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:44)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:325)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:304)
	at com.fiskaly.kassensichv.sma.SmaLoader.load(SmaLoader.java:110)
	at com.fiskaly.kassensichv.sma.GeneralSMA.<init>(GeneralSMA.java:11)

The file is there (and I also added all rights to exclude any problems concering rights)...

pi@gn_server:/tmp $ ls -la
insgesamt 14180
drwxrwxrwt 12 root root    4096 Sep 16 17:48 .
drwxr-xr-x 21 root root    4096 Nov 12  2018 ..
-rwxrwxrwx  1 pi   pi   7185348 Sep 16 17:29 com.fiskaly.kassensichv.sma-linux-arm.so

**Comment by pgaubatz** [comment]
Hi, is this a raspberry pi 1, or 2+?

**Comment by pgaubatz** [comment]
Hi again! Could you test it again with the `com.fiskaly.kassensichv.sma-linux-armel.so` library? You'd have to manually adapt the source code of the client library loader to use the `armel` suffix until we've added a hard-float/soft-float detection mechanism in the client libraries (something like https://github.com/java-native-access/jna/blob/cc1acdac02e4d0dda93ba01bbe3a3435b8933dab/src/com/sun/jna/Platform.java#L262)...

**Comment by cjaentsch** [comment]
It's a Raspberry Pi 3 Model B Plus Rev1.3

**Comment by pgaubatz** [comment]
> It's a Raspberry Pi 3 Model B Plus Rev1.3

Oh... then you should probably try loading the `arm64` variant...

**Comment by cjaentsch** [comment]
> > It's a Raspberry Pi 3 Model B Plus Rev1.3
> 
> Oh... then you should probably try loading the `arm64` variant...

As said in the "edit" of my comment, I'll try that tomorrow and report back.

**Comment by cjaentsch** [comment]
So, when using the "armel.so" I still get
`java.lang.UnsatisfiedLinkError: /tmp/com.fiskaly.kassensichv.sma-linux-arm.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden`

When using the "arm64.so" I get
`java.lang.UnsatisfiedLinkError: /tmp/com.fiskaly.kassensichv.sma-linux-arm.so: falsche ELF-Klasse: ELFCLASS64`

**Comment by cjaentsch** [comment]
I just wanted to ask if I can provide any more information concerning the Pi ARM issue...

**Comment by pgaubatz** [comment]
Hi, sorry for the delayed answer. Please try com.fiskaly.kassensichv.sma-linux-armhf.so (added in 340bfed8ade69b3e2310c1ea719538fb7142c04f).

**Comment by cjaentsch** [comment]
> Hi, sorry for the delayed answer. Please try com.fiskaly.kassensichv.sma-linux-armhf.so (added in [340bfed](https://github.com/fiskaly/fiskaly-kassensichv-sma/commit/340bfed8ade69b3e2310c1ea719538fb7142c04f)).

Thumbs up! This works!
