### ISSUE TITLE
504 Gateway Time-out - when trying to download TSS Data Export with many transactions

### ISSUE THREAD

**Issue by christian-rogobete** [fiskaly/fiskaly-kassensichv-sma#5]
Steps to reproduce:

1. Login to https://dashboard.fiskaly.com 
2. Choose a TSS with transaction counter > 2600 and signature counter > 4500
3. Trigger export (Perform full export)
4. Go to exports, wait until completed.
5. Press download when completed 
=> The result after waiting is "504 Gateway Time-out"

The same happens when trying to download by API.

Concrete example from fiskaltrust : TSS ID: 514c0930-2ce6-4edb-86b4-5f80936a4ce2

https://kassensichv.io/api/v0/tss/514c0930-2ce6-4edb-86b4-5f80936a4ce2/export/d4330c0d-d4d4-44db-9a36-4aacd66b62ab/file/b8ad8ed7-3796-488b-84fc-76adb4f9728d.tar

**Comment by pgaubatz** [comment]
Hi @christain-rogobete this repository has been deprecated.
